### ISSUE TITLE
inconsistent capitalization of output column names in differential_expression module

### ISSUE THREAD

**Issue by regenernate** [Benjamin-Vincent-Lab/binfotron#21]
Currently we save the two DeSeq2 parameters in the output .tsv with inconsistent capitalization:

colnames(deseq2_coef) = c("Deseq2_Intercept", "DeSeq2_Coef")

This should ideally use the more common DeSeq2_Intercept name.

**Comment by regenernate** [comment]
Per Dante, we should use DESeq2. 

When this is fixed, we will need to update pipelines that use de results for further analysis as the column names will have changed. For Nathan this includes:

TNBC_Target_Discovery
PRAD_TNBC_2024

**Comment by DanteBortone** [comment]
done
