### ISSUE TITLE
pvalue_nums sometimes puts the wrong number for the bin with highest value

### ISSUE THREAD

**Issue by regenernate** [Benjamin-Vincent-Lab/binfotron#22]
The final else statement in the pvalue_nums method ( in general_utilities.R ) always returns "> {barely_sig}" but if an additional_sig parameter has been provided, it needs to return "> {additional_sig}" instead.

**Comment by DanteBortone** [comment]
Added `sig_levels = c(0.05, 0.01, 0.001)`  and mproved function handle vectors now.
